### ISSUE TITLE
Error: client.profiles.listAllInResourceGroup is not a function

### ISSUE THREAD

**Issue by fiftin** [MicrosoftDocs/azure-docs-sdk-node#381]
Received error when trying run code from example (in Azure Function App). 
My code:
```javascript
const RestAzure = require('ms-rest-azure');
const TrafficManager = require('azure-arm-trafficmanager');

module.exports = function (context, myTimer) {
    RestAzure.loginWithServicePrincipalSecret('...', '...', '...').then(credentials => {
        const client = new TrafficManager(credentials, '...');
        return client.profiles.listAllInResourceGroup('test-traffic');
    }).then(profiles => {
        profiles.map(profile => {
            context.log(`found profile : ${profile.name}`);
        });
        context.done();
    }).catch(err => {
        context.log('Error: ' + err.message);
        context.done();
    });
};
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b10f74fe-dc7c-635e-86e8-d4c1094b7c6f
* Version Independent ID: 0d5ed087-ba6a-9e65-2eb4-49acae107138
* Content: [Azure Traffic Manager modules for Node.js](https://docs.microsoft.com/en-us/javascript/api/overview/azure/traffic-manager?view=azure-node-latest)
* Content Source: [docs-ref-services/traffic-manager.md](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/master/docs-ref-services/traffic-manager.md)
* Service: **traffic manager**
* Product: **azure**
* GitHub Login: @KumudD
* Microsoft Alias: **kumud**

**Comment by ramya-rao-a** [comment]
Thanks for reporting @fiftin and apologies for the delay in response

Looks like the page [Azure Traffic Manager modules for Node.js](https://docs.microsoft.com/en-us/javascript/api/overview/azure/traffic-manager?view=azure-node-latest) for which this issue was logged has been since updated and I don't see the above code snippet there.

Moreover, the `azure-arm-trafficmanager` package has been deprecated in favor of `@azure/arm-trafficmanager`
If you still see an error when using the latter, please log an issue at https://github.com/Azure/azure-sdk-for-js
