### ISSUE TITLE
Setup redirect for https://docs.microsoft.com/en-us/azure/app-service/app-service-web-get-started-nodejs

### ISSUE THREAD

**Issue by auchenberg** [MicrosoftDocs/azure-docs-sdk-node#495]
We should setup a redirect for https://docs.microsoft.com/en-us/azure/app-service/app-service-web-get-started-nodejs to point to the dev center.

Conversation is going on with the right team.

**Comment by KarlErickson** [comment]
@auchenberg I think what we need here is to update the links to this topic from within our dev-center topics so that the dev-center TOC is preserved when navigating within the dev center. The topic itself lives in the App Service docs so we can't redirect all external links (e.g. from search engines) to the dev-center TOC without moving the topic.

**Comment by KarlErickson** [comment]
Per our discussion, this topic is obsolete and the preferred content here is a topic in the dev-center quickstarts area. Also, we want customers who find this link on search engines (top ranked) to end up in the dev center, so a redirect is preferred.

**Comment by kraigb** [comment]
Completed in https://github.com/MicrosoftDocs/azure-docs-pr/pull/90392 per instructions on https://dev.azure.com/mseng/TechnicalContent/_boards/board/t/JavaScript%20on%20Azure/Stories/?workitem=1477013

**Comment by kraigb** [comment]
@KarlErickson or @auchenberg Can you close this?
