### ISSUE TITLE
DataLakeStoreAccountClient or DataLakeStoreAccountManagementClient

### ISSUE THREAD

**Issue by JeanBaptisteScellier** [MicrosoftDocs/azure-docs-sdk-node#582]
At [Azure Data Lake Store modules for Node.js](https://docs.microsoft.com/en-us/javascript/api/overview/azure/data-lake-store?view=azure-node-latest) there is an object DataLakeStoreAccountClient created in the example.
But in the doc there is no mention of it. Though there is DataLakeStoreAccountManagementClient. Is it the same thing? Which one should be used?

Same question with DataLakeStoreFileSystemClient and DataLakeStoreFileSystemManagementClient

**Comment by ramya-rao-a** [comment]
Thanks for reporting @JeanBaptisteScellier and our apologies for not responding sooner.

The page [Azure Data Lake Store modules for Node.js](https://docs.microsoft.com/en-us/javascript/api/overview/azure/data-lake-store?view=azure-node-latest) has since been updated multiple times and does not have a reference for DataLakeStoreAccountClient anymore.

Please log a new issue at https://github.com/Azure/azure-sdk-for-js for any questions on how to use the data lake store modules for nodejs
